name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

env:
  ITCH_USERNAME: hellhog
  ITCH_GAME_ID: perfect-plus1

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ['x86_64-linux', 'js-web', 'x86_64-win32', 'x86_64-macos']
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - uses: dapetcu21/setup-defold@v3.0.3
      - run: 'java -jar $BOB --archive --platform ${{ matrix.platform }} resolve distclean build bundle'
      - name: Set buildChannel based on platform
        id: set_build_channel
        run: |
          echo "gameData=build/default/Perfect+1/" >> $GITHUB_OUTPUT
          case "${{ matrix.platform }}" in
            js-web)
              echo "buildChannel=html" >> $GITHUB_OUTPUT
              ;;
            x86_64-linux)
              echo "buildChannel=linux" >> $GITHUB_OUTPUT
              ;;
            x86_64-win32)
              echo "buildChannel=windows" >> $GITHUB_OUTPUT
              ;;
            x86_64-macos)
              echo "buildChannel=mac" >> $GITHUB_OUTPUT
              echo "gameData=build/default/Perfect+1.app" >> $GITHUB_OUTPUT
              ;;
            *)
              echo "buildChannel=default" >> $GITHUB_OUTPUT
              ;;
          esac
      - name: Deploy to Itch.io
        # if: ${{ matrix.platform == 'js-web' }}
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{ secrets.BUTLER_API_KEY }}
          gameData: ${{ steps.set_build_channel.outputs.gameData }}
          itchUsername: ${{ env.ITCH_USERNAME }}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: ${{ steps.set_build_channel.outputs.buildChannel }}
          buildNumber: ${{ needs.version.outputs.version_hash }}
      - name: Export artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}
          path: ${{ steps.set_build_channel.outputs.gameData }}
